version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - 4001:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: osurl
      MYSQL_USER: osurl
      MYSQL_PASSWORD: osurl

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 4002:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  osurl:
    build: ./
    image: osurl
    ports:
      - 4003:80
    volumes: 
      - ./app:/var/www/html
    depends_on:
      - db