version: '3.9'

services:

  osurl_db:
    image: mysql:5.7
    ports:
      - 4001:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: osurl
      MYSQL_USER: osurl
      MYSQL_PASSWORD: osurl

  # osurl_phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 4002:80
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   depends_on:
  #     - osurl_db

  osurl:
    build:
      context: ./projects/osurl
    image: osurl
    ports:
      - 4003:80
    volumes:
      - ./projects/osurl/app:/var/www/html
    depends_on:
      - osurl_db
